M48
; DRILL file {KiCad (7.0.0)} date Mon Apr 24 03:13:19 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-24T03:13:19-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X4.4518Y-3.6339
X4.4518Y-3.8071
T2
X4.3858Y-4.8189
X4.4055Y-1.8465
X7.3504Y-1.8543
X7.3701Y-4.8228
T0
M30
